### ISSUE TITLE
No assets?

### ISSUE THREAD

**Issue by FatheredPuma81** [xoxor4d/t4-rtx#1]
Could you update the DEMO to include the assets?

**Comment by xoxor4d** [comment]
The demo mod on modDB should have everything that’s needed or do you mean something else?

**Comment by FatheredPuma81** [comment]
The Github and modDB are the same file and neither contains the rtx-remix folder which holds the assets shown in your YouTube video.

**Comment by FatheredPuma81** [comment]
Issue has been fix, thanks!
