### ISSUE TITLE
Issue with the rendering

### ISSUE THREAD

**Issue by HHasashi** [xoxor4d/t4-rtx#2]
Really weird rendering, the screens are at the high preset, it's nearly all white in lower presets.
![Call of Duty  World at War Screenshot 2024 02 24 - 02 24 12 83](https://github.com/xoxor4d/t4-rtx/assets/83731767/0741491c-4807-4dda-aaab-ffc5129c2099)
![Call of Duty  World at War Screenshot 2024 02 24 - 02 24 19 50](https://github.com/xoxor4d/t4-rtx/assets/83731767/0089e20c-8803-4730-bc5a-73c6f2cf9c43)

**Comment by xoxor4d** [comment]
I've added these light streak textures to the `ignore texture` list within remix - which is saved within the `rtx.conf` file that comes with t4-rtx. So seeing these on your screenshot means a) You didn't fully install t4-rtx or b) remix isn't being loaded correctly

**Comment by HHasashi** [comment]
I did the easy way as stated here : 

_**A. Easy way but might not feature the latest and greatest:
Download the latest [release](https://github.com/xoxor4d/t4-rtx/releases) and extract the contents into your CoDWaW root directory.
The in-game console should show t4-rtx-version > if the dll was loaded correctly.
If not, look at the [troubleshoot section](https://github.com/xoxor4d/t4-rtx#t4-rtx-is-not-being-loaded) further down.

Read the Dvars / Console Commands and Current issues sections**_

It did say "t4-rtx-version" in the console though.

EDIT : drivers are updated, config has Windows 10 with an RTX 2060.

**Comment by xoxor4d** [comment]
Can you re-extract the rtx.conf into your cod5 root folder that comes with the 1.0 release?

**Comment by HHasashi** [comment]
I'll try that

**Comment by HHasashi** [comment]
![Call of Duty  World at War Screenshot 2024 02 25 - 22 50 16 56](https://github.com/xoxor4d/t4-rtx/assets/83731767/f689571a-1be8-445e-b008-4f8e78b7cb55)

**Comment by HHasashi** [comment]
PROBLEM SOLVED : I dunno how I did though haha, thanks for the help and for the mod !
![Call of Duty  World at War Screenshot 2024 02 25 - 23 11 04 94](https://github.com/xoxor4d/t4-rtx/assets/83731767/9339d2d6-bd49-4cfc-9039-cba6814059db)
